import { hasCookie } from 'cookies-next'
import Head from 'next/head'
import { useEffect } from 'react'
import { useRouter } from 'next/router'
export default function Test(){
    const router = useRouter()
    useEffect(() => {
        if(!hasCookie('account_exist')) router.push('/signup')
        else router.push('/menPage')
    },[])
    return (
        <>
            <Head>
                <title>hairnetSocial</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </>
    )
}