import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from './header'
import CarouselBanner from './carousel'
import SignupForm from './login/form_signup'
import Footer from './footer'
import { hasCookie } from 'cookies-next'
import { useRouter } from 'next/router'
import {useEffect} from 'react'

const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  const router = useRouter()
  useEffect(()=>{
    if(hasCookie('account_exist')) router.push('/menPage')
  },[])
  return (
    <>
      <Head>
        <title>hairnetSocial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <CarouselBanner></CarouselBanner>
      <SignupForm></SignupForm>
      <Footer></Footer>
    </>
  )
}
