import AdminHeader from "./headeradmin"
import loginadcss from '../../styles/adminlogin.module.css'
import Head from "next/head"

export default function LoginAdmin(){
    return(
        <>
            {/* <Head>
                <title>hairnetSocial</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head> */}
            <AdminHeader></AdminHeader>
            <h1 className={loginadcss.title}>Login Admin</h1>
            <form action="/api/handleAdminAccount" className={loginadcss.form} method="POST">
                <label htmlFor="">User Name</label>
                <input type="text" name="usernameadmin" required/>
                <br />
                <label htmlFor="">Pasword</label>
                <input type="text" name="passadmin" required/>
                <br />
                <button>Login</button>
            </form>
        </>
    )
}