import Image from "next/image"
export default function ImageRank(props:any){
    const star = "/images/publicPageImages/star.png";
        if(props.rank ===0) return <></>
        else if(props.rank ===1) return (
            <Image 
                src={star}
                alt="picture"
                width={500}
                height={500}
                style={{width:'20px',height:'20px'}}>
            </Image>
        )
        else if(props.rank ===2) return (
            <>
                <Image 
                    src={star}
                    alt="picture"
                    width={500}
                    height={500}
                    style={{width:'20px',height:'20px'}}>
                </Image>
                <Image 
                    src={star}
                    alt="picture"
                    width={500}
                    height={500}
                    style={{width:'20px',height:'20px'}}>
                </Image>
            </>
        )
        else if(props.rank ===3) return (
            <>
                <Image 
                    src={star}
                    alt="picture"
                    width={500}
                    height={500}
                    style={{width:'20px',height:'20px'}}>
                </Image>
                <Image 
                    src={star}
                    alt="picture"
                    width={500}
                    height={500}
                    style={{width:'20px',height:'20px'}}>
                </Image>
                <Image 
                    src={star}
                    alt="picture"
                    width={500}
                    height={500}
                    style={{width:'20px',height:'20px'}}>
                </Image>
            </>
        )
        else if(props.rank ===4) return (
            <>
                <Image 
                    src={star}
                    alt="picture"
                    width={500}
                    height={500}
                    style={{width:'20px',height:'20px'}}>
                </Image>
                <Image 
                    src={star}
                    alt="picture"
                    width={500}
                    height={500}
                    style={{width:'20px',height:'20px'}}>
                </Image>
                <Image 
                    src={star}
                    alt="picture"
                    width={500}
                    height={500}
                    style={{width:'20px',height:'20px'}}>
                </Image>
                <Image 
                    src={star}
                    alt="picture"
                    width={500}
                    height={500}
                    style={{width:'20px',height:'20px'}}>
                </Image>
            </>
        )
        else if(props.rank ===5) return (
            <>
                <Image 
                    src={star}
                    alt="picture"
                    width={500}
                    height={500}
                    style={{width:'20px',height:'20px'}}>
                </Image>
                <Image 
                    src={star}
                    alt="picture"
                    width={500}
                    height={500}
                    style={{width:'20px',height:'20px'}}>
                </Image>
                <Image 
                    src={star}
                    alt="picture"
                    width={500}
                    height={500}
                    style={{width:'20px',height:'20px'}}>
                </Image>
                <Image 
                    src={star}
                    alt="picture"
                    width={500}
                    height={500}
                    style={{width:'20px',height:'20px'}}>
                </Image>
                <Image 
                    src={star}
                    alt="picture"
                    width={500}
                    height={500}
                    style={{width:'20px',height:'20px'}}>
                </Image>
            </>
        )
    return <></>
}