import admincss from '../../styles/adminPage.module.css';
import { useRouter } from 'next/router';
import AdminHeader from './headeradmin';
import Sidebar from './sidebarmenu';
export default function AdminPage(){
    const router = useRouter()
    console.log(router)
    return (
        <>
            {/* <Head>
                <title>hairnetSocial</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head> */}
            <AdminHeader></AdminHeader>
            <Sidebar></Sidebar>
            <div className={admincss.setshop}>
                <div className={admincss.title}>
                    <h1>Admin Page</h1>
                </div>
                <div className={admincss.form_set_shop}>
                    <form action="">
                        <label htmlFor="">Shop Name</label>
                        <input type="text" name='shopname'/>
                        <br />
                        <label htmlFor="">Shop Phone</label>
                        <input type="text" name='shopphone'/>
                        <br />
                        <label htmlFor="">Shop Email</label>
                        <input type="text" name='shopemail'/>
                        <br />
                        <label htmlFor="">Shop Address</label>
                        <input type="text" name='shopaddress'/>
                        <br />
                        <label htmlFor="">Shop Rank</label>
                        <input type="text" name='shoprank'/>
                        <br />
                        <button type='submit'>Submit</button>
                    </form>
                </div>
            </div>
        </>
    )
}
